import { now } from './gameLogic.js';

export function defaultState() {
  return {
    gold: 0,
    stage: 1,
    substage: 1,         // 1..10 per stage
    shards: 0,
    tapLevel: 1,
    tapBase: 2,
    critChance: 0.10,
    critMult: 5,
    skillActiveUntil: 0,
    skillCooldownUntil: 0,
    goldRushActiveUntil: 0,
    goldRushCooldownUntil: 0,
    bloodFrenzyActiveUntil: 0,
    bloodFrenzyCooldownUntil: 0,
    rallyCryActiveUntil: 0,
    rallyCryCooldownUntil: 0,
    luckyStrikeActiveUntil: 0,
    luckyStrikeCooldownUntil: 0,
    timeWarpActiveUntil: 0,
    timeWarpCooldownUntil: 0,
    bossEntered: false,  // true if player has entered the boss fight
    bossAttemptedThisStage: false,  // tracks if boss has been attempted in current stage
    heroes: [
      { id:"squire",      name:"Squire",      level: 0, baseDps: 2,   dpsMultPerLevel: 1.12, unlockStage: 1  },
      { id:"archer",      name:"Archer",      level: 0, baseDps: 6,   dpsMultPerLevel: 1.13, unlockStage: 8  },
      { id:"mage",        name:"Mage",        level: 0, baseDps: 30,  dpsMultPerLevel: 1.14, unlockStage: 18 },
      { id:"paladin",     name:"Paladin",     level: 0, baseDps: 150, dpsMultPerLevel: 1.15, unlockStage: 30 },
      { id:"necromancer",  name:"Necromancer",  level: 0, baseDps: 700,          dpsMultPerLevel: 1.16, unlockStage: 55  },
      { id:"druid",         name:"Druid",         level: 0, baseDps: 3000,         dpsMultPerLevel: 1.17, unlockStage: 70  },
      { id:"samurai",       name:"Samurai",       level: 0, baseDps: 12000,        dpsMultPerLevel: 1.18, unlockStage: 90  },
      { id:"warlock",       name:"Warlock",       level: 0, baseDps: 50000,        dpsMultPerLevel: 1.19, unlockStage: 115 },
      { id:"valkyrie",      name:"Valkyrie",      level: 0, baseDps: 200000,       dpsMultPerLevel: 1.20, unlockStage: 145 },
      { id:"dragonKnight",  name:"Dragon Knight", level: 0, baseDps: 800000,       dpsMultPerLevel: 1.21, unlockStage: 180 },
      { id:"shadowMonk",    name:"Shadow Monk",   level: 0, baseDps: 3000000,      dpsMultPerLevel: 1.22, unlockStage: 220 },
      { id:"archmage",      name:"Archmage",      level: 0, baseDps: 12000000,     dpsMultPerLevel: 1.23, unlockStage: 270 },
      { id:"titan",         name:"Titan",         level: 0, baseDps: 50000000,     dpsMultPerLevel: 1.24, unlockStage: 330 },
      { id:"celestial",     name:"Celestial",     level: 0, baseDps: 200000000,    dpsMultPerLevel: 1.25, unlockStage: 400 },
      { id:"voidLord",      name:"Void Lord",     level: 0, baseDps: 1000000000,   dpsMultPerLevel: 1.26, unlockStage: 500 },
    ],
    upgrades: {
      tap: 0,
      gold: 1,
      idle: 1,
      critC: 1,
      critM: 1,
    },
    shardUpgrades: { goldBonus: 0, bossTime: 0, prestigeBonus: 0, headStart: 0, tapSynergy: 0, heroMastery: 0, luckyStrike: 0, killingBlow: 0, bossBane: 0, soulCollector: 0, tapMastery: 0, powerSurgeDuration: 0, goldRushDuration: 0, bloodFrenzyDuration: 0, rallyCryDuration: 0, luckyStrikeDuration: 0, timeWarpDuration: 0 },
    shardUpgradeUnlocked: {},
    milestones: { sharpening: false, formation: false, dragonsLuck: false, goldVein: false },
    lifetimeGold: 0,
    highestStage: 1,
    ascensionCount: 0,
    totalTaps: 0,
    achievements: {},
    lastTick: now(),
    lastSave: now(),
    saveVersion: 2,
  };
}